### ISSUE TITLE
Range Labels don't align when using arcDegreeScale

### ISSUE THREAD

**Issue by dakota-kallas** [shipt/segmented-arc-for-react-native#84]
The range labels don't properly align when you use the custom arcDegreeScale property on a segment. This functionality was introduced in #70
![labels](https://github.com/shipt/segmented-arc-for-react-native/assets/79180508/627a4a48-c52d-4aa2-ba55-4eec37ae184f)

**Comment by rkyle35242** [comment]
@dakota-kallas oooooooooo good catch, I'll see if I can get this resolved tomorrow

**Comment by rkyle35242** [comment]
I have a fix incoming that will allow aligning range displays with segments. Updates will be reflected in the README as well for usage.
